# Generated by Django 3.0 on 2020-12-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bookingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='people',
            field=models.IntegerField(),
        ),
    ]
