# Generated by Django 3.0 on 2020-12-14 06:18

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201214_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
