# Generated by Django 3.0 on 2020-12-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201214_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefmodel',
            name='image',
            field=models.ImageField(upload_to='chef/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='image',
            field=models.ImageField(upload_to='menu_images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='testimonialmodel',
            name='image',
            field=models.ImageField(upload_to='testimonials/%Y/%m/%d'),
        ),
    ]
