# Generated by Django 3.0 on 2020-12-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201214_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='specials/%Y/%m/%d')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'special offer',
                'verbose_name_plural': 'special offers',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='bookingmodel',
            options={'verbose_name': 'Table Booking', 'verbose_name_plural': 'Table Bookings'},
        ),
        migrations.AlterModelOptions(
            name='chefmodel',
            options={'ordering': ('name',), 'verbose_name': 'chef', 'verbose_name_plural': 'chefs'},
        ),
        migrations.AlterModelOptions(
            name='gallerymodel',
            options={'ordering': ('image_name',), 'verbose_name': 'image gallery', 'verbose_name_plural': 'image gallery'},
        ),
        migrations.AlterModelOptions(
            name='menumodel',
            options={'ordering': ('name',), 'verbose_name': 'menu item', 'verbose_name_plural': 'menu items'},
        ),
        migrations.AlterModelOptions(
            name='testimonialmodel',
            options={'ordering': ('name',), 'verbose_name': 'testimonial', 'verbose_name_plural': 'testimonials'},
        ),
    ]
