# Generated by Django 3.0 on 2020-12-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_eventsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Newletter',
            },
        ),
    ]
